version: '3.8'

services:

  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: user123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  client:
    build: ./client  
    ports: 
      - "8084:8080"
    depends_on: 
      - db

  product:
    build: ./product  
    ports: 
      - "8083:8080"
    depends_on: 
      - db

  quotation:
    build: ./quotation 
    ports: 
      - "8082:8080"
    depends_on: 
      - db
      - redis

  sales:
    build: ./sales
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - client
      - product
      - quotation

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./scripts/proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80
    depends_on:
      - client
      - product
      - quotation
      - sales

volumes:
  redis_data: