version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: TCF_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_USER: user
      MYSQL_PASSWORD: user123

  dotnetapp:
    build: 
      context: .
      dockerfile: api/Dockerfile
    container_name: TCF_container
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      CONNECTION_STRING: "Port=3306;Uid=root;Pwd=user123"
