version: '3.8'

services:
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  client:
    build: ./client  
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  product:
    build: ./product  
    ports: 
      - "7070:7070"
    depends_on: 
      - db