version: '3.8'

services:
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  client:
    build: ./client  
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  product:
    build: ./product  
    ports: 
      - "7070:7070"
    depends_on: 
      - db

  quotation:
    build: ./quotation 
    ports: 
      - "6060:6060"
    depends_on: 
      - db
      - redis

volumes:
  redis_data: