version: '3.8'

services:
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_USER: user
#  api:
#    image: api
#    build: .
#    ports: 
#      - "8080:8080"
#    depends_on: 
#      - db